export type Comentario = {
  usuario: string
  texto: string
}

export interface Lugar {
  id: number
  nombre: string
  direccion: string
  descripcion: string
  resena: string
  presupuesto: string
  imagen: string
  horarioApertura: string
  horarioCierre: string
  diasAbierto: string[]
  etiquetas: string[]   // nuevo campo
}


export const lugares: Lugar[] = [
  {
    id: 1,
    nombre: "Pergamino Café",
    direccion: "Cra. 37 #8A-37, El Poblado",
    descripcion: "Cafetería de especialidad, referente de café de calidad en la ciudad.",
    resena: "⭐⭐⭐⭐⭐ (4.7/5)",
    presupuesto: "$20.000 - $40.000",
    imagen: "https://lh3.googleusercontent.com/p/AF1QipNkBThQyr6BQaL75wjkk1klil8FLM4KJFtB4y2l=s680-w680-h510-rw",
    horarioApertura: "07:00 AM",
    horarioCierre: "10:00 PM",
    diasAbierto: ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"],
    etiquetas: ["Café", "Especialidad", "El Poblado", "Trabajar", "Acogedor"]
  },
  {
    id: 2,
    nombre: "Hija Mia Café",
    direccion: "Cl. 35 #8-34, El Poblado",
    descripcion: "Café acogedor con deliciosos postres y opciones para celiacos.",
    resena: "⭐⭐⭐⭐⭐ (4.8/5)",
    presupuesto: "$18.000 - $38.000",
    imagen: "https://lh3.googleusercontent.com/p/AF1QipNkBThQyr6BQaL75wjkk1klil8FLM4KJFtB4y2l=s680-w680-h510-rw",
    horarioApertura: "08:00 AM",
    horarioCierre: "09:00 PM",
    diasAbierto: ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"],
    etiquetas: ["Café", "Postres", "Sin Gluten", "Acogedor", "El Poblado"]
  },
  {
    id: 3,
    nombre: "Al Alma Café",
    direccion: "Av. 39d #74B #39-143, Laureles - Estadio, Medellín",
    descripcion: "Espacio tranquilo con comida saludable y un ambiente ideal para trabajar.",
    resena: "⭐⭐⭐⭐ (4.6/5)",
    presupuesto: "$22.000 - $45.000",
    imagen: "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSz6xM-lWX0aIIlQEPsUvGAB7tRbMWYZGFSsT3ozAXmGoup0YeEYiAYuwAGvOpX1KClkiuus7xqfWTW9H-mG3nPEHC0oITdevBaMNhnrLrGqrbiZO9TEmabAt8RGv0g0O_uhn-UeUhyNT-A=s680-w680-h510-rw",
    horarioApertura: "08:30 AM",
    horarioCierre: "09:30 PM",
    diasAbierto: ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"],
    etiquetas: ["Saludable", "Trabajar", "Comida Fit", "Laureles", "Tranquilo"]
  },
  {
    id: 4,
    nombre: "Café Velvet",
    direccion: "Cra. 37 #8a-46, El Poblado, Medellín",
    descripcion: "Bar de vinos y café con una atmósfera íntima y sofisticada.",
    resena: "⭐⭐⭐⭐ (4.5/5)",
    presupuesto: "$25.000 - $55.000",
    imagen: "https://lh3.googleusercontent.com/p/AF1QipOd9h18FC_d6jsUK0FXZiRuuu-aTYBnFuEyyhSn=s680-w680-h510-rw",
    horarioApertura: "04:00 PM",
    horarioCierre: "12:00 AM",
    diasAbierto: ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado"],
    etiquetas: ["Bar", "Vinos", "Café", "Íntimo", "Sofisticado", "El Poblado"]
  },
  {
    id: 5,
    nombre: "Rituales Compañía de Café",
    direccion: "Cq. 6 #39b-22, Laureles - Estadio, Medellín",
    descripcion: "Café en el centro comercial San Diego, ideal para una pausa en el plan de compras.",
    resena: "⭐⭐⭐⭐ (4.3/5)",
    presupuesto: "$15.000 - $30.000",
    imagen: "https://lh3.googleusercontent.com/p/AF1QipPjhnhYjkj-ZVzpXwZB7arn0pfH-aXs3a0WbIL8=s680-w680-h510-rw",
    horarioApertura: "09:00 AM",
    horarioCierre: "09:00 PM",
    diasAbierto: ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"],
    etiquetas: ["Café", "Centro Comercial", "Laureles", "Compras", "Pausa"]
  },
  {
    id: 6,
    nombre: "La Gatoria Cat Cafe",
    direccion: "Cra. 80C #33-84, Laureles - Estadio, Medellín",
    descripcion: "Cafetería con gatos, ideal para amantes de los felinos.",
    resena: "⭐⭐⭐⭐ (4.7/5)",
    presupuesto: "$40,000-60,000",
    imagen: "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSwlco2zVnYbTpBQhtU7R4wzp5XIdcAjMbRJWggOUBLm0aj11hVH4HsrK4RXWFucjVoAEthXZrjFFYG_WxYX_tsJHrF21OYs1WFfr4UJ3_epPk3ynyjYnviWH18Li_QEGE3fRhcgBaT-Uj_Z=s680-w680-h510-rw",
    horarioApertura: "10:00 AM",
    horarioCierre: "08:00 PM",
    diasAbierto: ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"],
    etiquetas: ["Gatos", "Café", "Mascotas", "Laureles", "Diferente"]
  },
  {
    id: 7,
    nombre: "Museo de Antioquia",
    direccion: "Cl. 52 #52-43, La Candelaria, Medellín",
    descripcion: "Alberga una vasta colección de arte, incluyendo obras de Fernando Botero.",
    resena: "⭐⭐⭐⭐⭐ (4.6/5)",
    presupuesto: "$20.000 (Entrada)",
    imagen: "https://lh3.googleusercontent.com/p/AF1QipNqXffczcrQOepDyQ_5za6nXuthowHd2XlniSkf=s680-w680-h510-rw",
    horarioApertura: "10:00 AM",
    horarioCierre: "05:30 PM",
    diasAbierto: ["Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"],
    etiquetas: ["Museo", "Arte", "Botero", "Cultural", "Histórico", "Centro"]
  },
  {
    id: 8,
    nombre: "Casa Museo Pedro Nel Gómez",
    direccion: "Cra 51 B #8524, Aranjuez, Medellín",
    descripcion: "Museo en la casa del artista, con sus murales y obras.",
    resena: "⭐⭐⭐⭐ (4.5/5)",
    presupuesto: "$10.000 (Entrada)",
    imagen: "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSwvT9IfbLwKFQN8wvU7kAdtVZGJdOC0xHL8RX1Fe8tOTtP4ZCWX3wnXSQF8SJxdXbYdGxio7kjcyGHHWRRmhMDAKxUHunHQHcEfRQUkQa7MexQ6uk3aNGGBtpwomL-etPr0s21X=s680-w680-h510-rw",
    horarioApertura: "09:00 AM",
    horarioCierre: "05:00 PM",
    diasAbierto: ["Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"],
    etiquetas: ["Museo", "Arte", "Histórico", "Cultural", "Aranjuez"]
  },
  {
    id: 9,
    nombre: "Palacio de la Cultura Rafael Uribe Uribe",
    direccion: "Cra. 51 #52-03, Centro",
    descripcion: "Icono arquitectónico de Medellín, con exposiciones y tours guiados.",
    resena: "⭐⭐⭐⭐ (4.7/5)",
    presupuesto: "Gratis - $10.000",
    imagen: "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSxJPs5kHKYl5ccb5Mvb8FB6H2pygOT2B9erfTal-0spAsDFbCXNyMTPSEHEHKaFfb3clQ0plZa83bJxKqglegOpyelay0qVmVgLpLIkyDiQCshFtiupfHApuP4NZWBXwqUmV0EAFJatDOQ=s680-w680-h510-rw",
    horarioApertura: "08:00 AM",
    horarioCierre: "06:00 PM",
    diasAbierto: ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado"],
    etiquetas: ["Arquitectura", "Cultural", "Histórico", "Centro", "Gratis"]
  },
  {
    id: 10,
    nombre: "Galería de la Oficina",
    direccion: "Cl 10 #40-37, El Poblado, Envigado, Medellín",
    descripcion: "Galería de arte contemporáneo en el corazón de Medellín.",
    resena: "⭐⭐⭐⭐ (4.7/5)",
    presupuesto: "Gratis",
    imagen: "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSz6W7j4vBYtkibfVEu3eIdM3wJCwCJexRdeUnU72OB7WqIoqS3zShrYkZDP4D3gIJzod8d8oVkWXed-xfvfmS315hcRDSbPMiQMWBMtNaUvtyt8l52ZuMpeB2nN60bg0LIEjfvg=s680-w680-h510-rw",
    horarioApertura: "10:00 AM",
    horarioCierre: "07:00 PM",
    diasAbierto: ["Martes", "Miércoles", "Jueves", "Viernes", "Sábado"],
    etiquetas: ["Galería", "Arte", "Contemporáneo", "El Poblado", "Gratis"]
  },
  {
    id: 11,
    nombre: "Museo de Arte Moderno de Medellín",
    direccion: "Cra 44 #19a-100, El Poblado, Medellín",
    descripcion: "Espacio cultural en la zona de Ciudad del Río, cerca del MAMM.",
    resena: "⭐⭐⭐⭐ (4.7/5)",
    presupuesto: "$15.000 - $25.000",
    imagen: "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSxz5Fuaf0ctGuR7cnXm326Oj8gsRupdSw30rawhpZH5kG7_KKpDP1UuFmVOZxRNrqphfBtgDPoImEsSy76QEh65TFQYyStc83j5QpV_DgDlrHA-J59mW1mDy8KXQbiBX6PGK0rMIA=s680-w680-h510-rw",
    horarioApertura: "09:00 AM",
    horarioCierre: "06:00 PM",
    diasAbierto: ["Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"],
    etiquetas: ["Museo", "Arte Moderno", "Cultural", "El Poblado", "MAMM"]
  },
  {
    id: 12,
    nombre: "Parque de los Pies Descalzos",
    direccion: "Cra. 58 #42-125, La Candelaria, Medellín",
    descripcion: "Experiencia sensorial para caminar descalzo sobre diferentes texturas.",
    resena: "⭐⭐⭐⭐ (4.5/5)",
    presupuesto: "Gratis",
    imagen: "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSy3mkE-KsCw54v-BfzDNFeqZrOTX6GpU-t2uIOOfjrWyYmUPMYNdzh8RDzpLE79Lx4VG8DZ604JnW2eLcsDerLReb-uiQCHg78SQnvCzRzNY2j-R2uIRG11Z7TFRYTqe0viqv9S6g=s680-w680-h510-rw",
    horarioApertura: "06:00 AM",
    horarioCierre: "10:00 PM",
    diasAbierto: ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"],
    etiquetas: ["Parque", "Sensorial", "Gratis", "Familiar", "Centro"]
  },
  {
    id: 13,
    nombre: "Plaza Botero",
    direccion: "Cl. 52 #52-43, La Candelaria, Medellín",
    descripcion: "Plaza icónica con 23 esculturas monumentales de Fernando Botero.",
    resena: "⭐⭐⭐⭐ (4.6/5)",
    presupuesto: "Gratis",
    imagen: "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSyfHzSSTw4n6SGX4cZDC6f7xnXzcWssDve7UPkeZ4SUZlYhy_By9bbQ0DKSHJ53YHsnFCHv2ito41ePOtTXtn4l9g8UjJCmtjFF9n_1aCA1ZCTXS46BT_8e_DtEvHkww_mEplR_=s680-w680-h510-rw",
    horarioApertura: "24 horas",
    horarioCierre: "24 horas",
    diasAbierto: ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"],
    etiquetas: ["Plaza", "Botero", "Esculturas", "Gratis", "24 horas", "Icono"]
  },
  {
    id: 14,
    nombre: "Parque Arví",
    direccion: "Vía a, Piedras Blancas, Medellín",
    descripcion: "Parque ecoturístico público, ideal para caminatas y conexión con la naturaleza.",
    resena: "⭐⭐⭐⭐⭐ (4.7/5)",
    presupuesto: "Gratis (Costo transporte)",
    imagen: "https://antioquiahoy.co/wp-content/uploads/2025/05/Imagen-de-WhatsApp-2023-08-01-a-las-14.01.47.jpg",
    horarioApertura: "09:00 AM",
    horarioCierre: "05:00 PM",
    diasAbierto: ["Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"],
    etiquetas: ["Parque", "Naturaleza", "Ecoturismo", "Senderismo", "Familiar"]
  },
  {
    id: 15,
    nombre: "Jardín Botánico de Medellín",
    direccion: "Cl. 73 #51D-14, Aranjuez, Medellín",
    descripcion: "Pulmón verde de la ciudad con una gran variedad de flora.",
    resena: "⭐⭐⭐⭐⭐ (4.7/5)",
    presupuesto: "Gratis",
    imagen: "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSyXLVd1miK9j7GX6qW3QgUSgycEcTGcEl9LOi89vLD7MoijRJLayiQTHLt4JtHylWWlA3GN_Ho92zZVQ_wgwCIZ4_9RewricvhfdW456ouWlwyv9WoF39cGari4U-6SQvCh1xk29g=s680-w680-h510-rw",
    horarioApertura: "09:00 AM",
    horarioCierre: "05:00 PM",
    diasAbierto: ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"],
    etiquetas: ["Jardín", "Naturaleza", "Gratis", "Familiar", "Flora", "Aranjuez"]
  },
  {
    id: 16,
    nombre: "Mirador Cerro El Volador",
    direccion: "Medellín, Robledo, Medellín",
    descripcion: "El cerro más alto de la ciudad, con vistas panorámicas de 360 grados.",
    resena: "⭐⭐⭐⭐ (4.6/5)",
    presupuesto: "Gratis",
    imagen: "https://www.medellin.travel/wp-content/uploads/elementor/thumbs/0004_CV001-p9zifbkts2qgjj4y61sqld5adhxrysk62a32jk3w2o.jpg",
    horarioApertura: "06:00 AM",
    horarioCierre: "06:00 PM",
    diasAbierto: ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"],
    etiquetas: ["Mirador", "Cerro", "Vistas", "Gratis", "Panorámico", "Robledo"]
  },
  {
    id: 17,
    nombre: "Salon Malaga",
    direccion: "Cra. 51 #45-80, La Candelaria, Medellín",
    descripcion: "Bar histórico con música tango y antioqueñidad pura.",
    resena: "⭐⭐⭐⭐ (4.5/5)",
    presupuesto: "$20.000 - $40.000",
    imagen: "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSzwj0kKT0gloLCaIo_GVNwClQZ2E9SAJEpDtHx2OPeZ4ySX1IuTrMsv7HrDjMXopwulKPlzg5g6whXdGCfZvezf8cxML7d_pOdk9RK928Qkz7U2ugTQBuOb3MW26f4aQw4SVcE-lksLhdg=s680-w680-h510-rw",
    horarioApertura: "10:00 AM",
    horarioCierre: "02:00 AM",
    diasAbierto: ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado"],
    etiquetas: ["Bar", "Histórico", "Tango", "Antioqueño", "Centro", "Cultural"]
  },
  {
    id: 18,
    nombre: "37 Park",
    direccion: "Cra. 37 #8a-4, El Poblado, Medellín",
    descripcion: "Parque de comida y bar al aire libre, muy popular los fines de semana.",
    resena: "⭐⭐⭐⭐ (4.4/5)",
    presupuesto: "$30.000 - $60.000",
    imagen: "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSwWz0-YJiqUq5xVMNcPxhIIqlwTdGDdqd7muZVKMFZ3tRpSSNvPANRoYHyEnVHRFET1tHu-c5OGlGtaM0OILqFgzP0My3uTC6Dgpur_yzjJqItCB3JRvyKctDhAn0QIo8kRR4rwLzA0voDb=s680-w680-h510-rw",
    horarioApertura: "12:00 PM",
    horarioCierre: "12:00 AM",
    diasAbierto: ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"],
    etiquetas: ["Food Park", "Aire Libre", "El Poblado", "Comida", "Bar", "Social"]
  },
  {
    id: 19,
    nombre: "Vintrash Bar",
    direccion: "Cra. 35 #8A-39, El Poblado, Medellín",
    descripcion: "Bar emblemático de la Zona Rosa, con música alternativa y rock.",
    resena: "⭐⭐⭐⭐ (4.3/5)",
    presupuesto: "$25.000 - $50.000",
    imagen: "https://lh3.googleusercontent.com/p/AF1QipPDrz3raytGvcy3wMyvYMSLk8dLFAG8Lq9EmDTv=s680-w680-h510-rw",
    horarioApertura: "05:00 PM",
    horarioCierre: "03:00 AM",
    diasAbierto: ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado"],
    etiquetas: ["Bar", "Rock", "Alternativo", "Zona Rosa", "El Poblado", "Emblemático"]
  },
  {
    id: 20,
    nombre: "Mojitos Restaurant Bar",
    direccion: "Cra. 36 #10b 28 Segundo Piso. Local 201, El Poblado, Medellín",
    descripcion: "Restaurante-bar vibrante con shows en vivo, cantantes y DJ.",
    resena: "⭐⭐⭐⭐⭐ (4.9/5)",
    presupuesto: "$40,000 - $80,000",
    imagen: "https://lh3.googleusercontent.com/p/AF1QipPWQmHwSp-8C1qxqPh1hJuMPfDP7c_oloUO9gUX=s680-w680-h510-rw",
    horarioApertura: "06:00 PM",
    horarioCierre: "03:00 AM",
    diasAbierto: ["Miércoles", "Jueves", "Viernes", "Sábado"],
    etiquetas: ["Restaurante", "Bar", "Shows en Vivo", "Música", "El Poblado", "Vibrante"]
  },
  {
    id: 21,
    nombre: "The Terrace by Wellcomm",
    direccion: "Cra. 43E #11-37, El Poblado, Medellín",
    descripcion: "Rooftop moderno con ambiente sofisticado, ideal para disfrutar de cócteles y pizzas con vista al cielo.",
    resena: "⭐⭐⭐⭐⭐ (4.9/5)",
    presupuesto: "$50,000 - $90,000",
    imagen: "https://resizer.otstatic.com/v2/photos/huge/1/79602324.jpg",
    horarioApertura: "04:00 PM",
    horarioCierre: "02:00 AM",
    diasAbierto: ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado"],
    etiquetas: ["Rooftop", "Sofisticado", "Cócteles", "Vistas", "El Poblado", "Moderno"]
  },
  {
    id: 22,
    nombre: "Sputnik Bar",
    direccion: "Pasaje Cervantes, Cra. 42A #48-89, La Candelaria, Medellín",
    descripcion: "Bar de ambiente alternativo con buena música, precios accesibles y atención amable.",
    resena: "⭐⭐⭐⭐ (4.7/5)",
    presupuesto: "$25,000 - $45,000",
    imagen: "https://lh3.googleusercontent.com/p/AF1QipMM7-1tnCMmllFrU46HtMmLTTs4zEmfQ8J_MRGn=s680-w680-h510-rw",
    horarioApertura: "05:00 PM",
    horarioCierre: "02:00 AM",
    diasAbierto: ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado"],
    etiquetas: ["Bar", "Alternativo", "Accesible", "Música", "Centro", "Bohemio"]
  },
  {
    id: 23,
    nombre: "Bantú Bar",
    direccion: "Cl. 65 #55a-35, La Candelaria, Medellín",
    descripcion: "Bar popular conocido por sus buenos precios en licor y ambiente casual para reunirse con amigos.",
    resena: "⭐⭐⭐⭐ (4.4/5)",
    presupuesto: "$20,000 - $40,000",
    imagen: "https://lh3.googleusercontent.com/p/AF1QipNFzrao8FmvMpREPjmTEugzosNT1PjV5CkJboHs=s680-w680-h510-rw",
    horarioApertura: "04:00 PM",
    horarioCierre: "02:00 AM",
    diasAbierto: ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado"],
    etiquetas: ["Bar", "Popular", "Económico", "Amigos", "Centro", "Casual"]
  },
  {
    id: 24,
    nombre: "La Jaus Pub Rock",
    direccion: "Pasaje Cervantes, Cra. 42A #48-46, Medellín",
    descripcion: "Parrilla y pub rockero con excelente música, personal amable y precios accesibles en cerveza.",
    resena: "⭐⭐⭐⭐ (4.7/5)",
    presupuesto: "$40,000 - $60,000",
    imagen: "https://lh3.googleusercontent.com/p/AF1QipMUdhtKUgQTvzRe8-_BI-APx1fqy7qj-_9edNZ8=s680-w680-h510-rw",
    horarioApertura: "05:00 PM",
    horarioCierre: "02:00 AM",
    diasAbierto: ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado"],
    etiquetas: ["Pub", "Rock", "Parrilla", "Cerveza", "Centro", "Amigable"]
  },
  {
    id: 25,
    nombre: "Victoria Roof Garden",
    direccion: "Cra. 35 #8A-73, El Poblado, Medellín",
    descripcion: "Terraza-jardín multifuncional que funciona como restaurante, bar y discoteca con precios razonables.",
    resena: "⭐⭐⭐⭐ (4.7/5)",
    presupuesto: "$45,000 - $75,000",
    imagen: "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSyoatKNC3t7HDlZFNG--EtQW-HASr61P4SGghO8TZPlGKl5xc6X-nkACI78pw9Vkclp8WeEX_L49IAJXEFPnYi7nMmRmdl0X6T5rBOI4bY6XA89MJ_M4iD5fiGOdizE1ayCQMRr=s680-w680-h510-rw",
    horarioApertura: "06:00 PM",
    horarioCierre: "03:00 AM",
    diasAbierto: ["Miércoles", "Jueves", "Viernes", "Sábado"],
    etiquetas: ["Rooftop", "Jardín", "Multifuncional", "Discoteca", "El Poblado", "Terraza"]
  },
  {
    id: 26,
    nombre: "La Octava Bar",
    direccion: "Cl. 8 #37a-49, El Poblado, Medellín",
    descripcion: "Bar con terraza en la Zona Rosa, conocido por sus buenos cócteles, música y precios moderados.",
    resena: "⭐⭐⭐⭐ (4.6/5)",
    presupuesto: "$30,000 - $55,000",
    imagen: "https://lh3.googleusercontent.com/p/AF1QipMupTjkfvkD7sSU0e-kMJAqOmvbiHHJ23Ue-sRU=w289-h312-n-k-no",
    horarioApertura: "05:00 PM",
    horarioCierre: "02:00 AM",
    diasAbierto: ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado"],
    etiquetas: ["Bar", "Terraza", "Cócteles", "Zona Rosa", "El Poblado", "Moderado"]
  },
  {
    id: 27,
    nombre: "Del Patio Bar",
    direccion: "Cq. 2 #7029, Laureles - Estadio, Medellín",
    descripcion: "Parrilla-bar con un ambiente agradable, buena música, buen servicio y precios competitivos.",
    resena: "⭐⭐⭐⭐ (4.4/5)",
    presupuesto: "$60,000 - $80,000",
    imagen: "https://www.tripadvisor.co/Restaurant_Review-g297478-d5980952-Reviews-Al_Patio_Restaurante_Bar-Medellin_Antioquia_Department.html",
    horarioApertura: "12:00 PM",
    horarioCierre: "11:00 PM",
    diasAbierto: ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"],
    etiquetas: ["Parrilla", "Bar", "Laureles", "Agradable", "Competitivo", "Comida"]
  },
  {
    id: 28,
    nombre: "Donde Aquellos Bar",
    direccion: "Cra. 38 #9A-26, El Poblado, Medellín",
    descripcion: "Bar acogedor y de ambiente relajado, perfecto para grupos que buscan precios asequibles.",
    resena: "⭐⭐⭐⭐ (4.4/5)",
    presupuesto: "$25,000 - $50,000",
    imagen: "https://lh3.googleusercontent.com/p/AF1QipOrD4ukP4sOX7Nh0r1gzE-XfgbqU17DmUJwkhx-=s680-w680-h510-rw",
    horarioApertura: "05:00 PM",
    horarioCierre: "02:00 AM",
    diasAbierto: ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado"],
    etiquetas: ["Bar", "Acogedor", "Relajado", "Grupos", "Asequible", "El Poblado"]
  },
  {
    id: 29,
    nombre: "Trilogía Bar",
    direccion: "Cra 43G #24-08, El Poblado, Medellín",
    descripcion: "Bar de alta gama con un ambiente exclusivo, ideal para experiencias premium y cócteles de autor.",
    resena: "⭐⭐⭐⭐ (4.7/5)",
    presupuesto: "$100,000+",
    imagen: "https://lh3.googleusercontent.com/p/AF1QipM_KkDzLB9yOokmKZl19OH75JL1CdGUzett2k87=s680-w680-h510-rw",
    horarioApertura: "07:00 PM",
    horarioCierre: "03:00 AM",
    diasAbierto: ["Miércoles", "Jueves", "Viernes", "Sábado"],
    etiquetas: ["Bar", "Alta Gama", "Exclusivo", "Premium", "Cócteles Autor", "El Poblado"]
  },
  {
    id: 30,
    nombre: "Berlin 1930 Bar",
    direccion: "Cl 10 #41-65, El Poblado, Medellín",
    descripcion: "Bar temático con un ambiente único y bien logrado. Ideal para tomar cerveza y disfrutar la vibra.",
    resena: "⭐⭐⭐⭐ (4.6/5)",
    presupuesto: "$40,000 - $60,000",
    imagen: "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSxrZrUb9AM3VK_g9EV3ctRe_BU_PR272jOdlhz27VE3Fa-pCtdBQJWV7lWhOuG3RDU8VxADdlk1uLtKZ6OcuqsT0cALIADOgIjMRJzP69Pt4Q7AyPVGOyKctcYvaHZgfo6oN9gL=s680-w680-h510-rw",
    horarioApertura: "06:00 PM",
    horarioCierre: "02:00 AM",
    diasAbierto: ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado"],
    etiquetas: ["Bar", "Temático", "Cerveza", "Único", "El Poblado", "Ambiente"]
  },
  {
    id: 31,
    nombre: "Ene Rooftop",
    direccion: "Carrera 35 # 8a - 72 3er piso o interior 301, Medellín",
    descripcion: "Pub en terraza con un ambiente relajado, buenos precios y calidad en sus productos y cócteles.",
    resena: "⭐⭐⭐⭐ (4.4/5)",
    presupuesto: "$35,000 - $60,000",
    imagen: "https://lh3.googleusercontent.com/p/AF1QipNlzofCMD4hxAK9YBpzy732vUTWuCUPYX_hcmM7=w289-h312-n-k-no",
    horarioApertura: "05:00 PM",
    horarioCierre: "02:00 AM",
    diasAbierto: ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado"],
    etiquetas: ["Rooftop", "Pub", "Relajado", "Cócteles", "El Poblado", "Calidad"]
  },
  {
    id: 32,
    nombre: "Café Revolución",
    direccion: "Carrera 73 |, Cq. 4 ##6, Medellín",
    descripcion: "Café industrial en Boston, famoso por su pan de bono y ambiente auténtico.",
    resena: "⭐⭐⭐⭐ (4.4/5)",
    presupuesto: "$12,000 - $25,000",
    imagen: "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSxuFptuCIhLiZ1cRGqrvvKOs393tZvoqEFIZmG4eIKmGgB5ocSPUDBn2OnzrBmhWOA6MuX1H9NF5DmqEFR_JQIBmL5xMewze0I8kBRfDi5Bl6HJCP6oP30v3zDOjck-jQe7CJKpFw=s680-w680-h510-rw",
    horarioApertura: "08:00 AM",
    horarioCierre: "10:00 PM",
    diasAbierto: ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"],
    etiquetas: ["Café", "Industrial", "Pan de Bono", "Auténtico", "Boston", "Económico"]
  },
  {
    id: 33,
    nombre: "Mercado del Río",
    direccion: "050021, Cl. 24 #48-28, Medellín",
    descripcion: "Primer food hall de Colombia, con +50 opciones gastronómicas en un solo lugar.",
    resena: "⭐⭐⭐⭐ (4.5/5)",
    presupuesto: "$20,000 - $50,000",
    imagen: "https://lh3.googleusercontent.com/p/AF1QipPc58BicltoRWi6AFl03Mk5AYYewUSBV032AHH3=s680-w680-h510-rw",
    horarioApertura: "11:00 AM",
    horarioCierre: "11:00 PM",
    diasAbierto: ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"],
    etiquetas: ["Food Hall", "Variedad", "Gastronomía", "Moderno", "Opción Múltiple"]
  },
  {
    id: 34,
    nombre: "Carmen",
    direccion: "Cra. 36 #10a-27, El Poblado, Medellín",
    descripcion: "Restaurante de alta cocina colombiana, ideal para ocasiones especiales.",
    resena: "⭐⭐⭐⭐⭐ (4.8/5)",
    presupuesto: "$150,000",
    imagen: "https://lh3.googleusercontent.com/p/AF1QipPKxxagHQHW4YNu0UbOra12_t10onc3ZFwuXedX=s680-w680-h510-rw",
    horarioApertura: "12:00 PM",
    horarioCierre: "11:00 PM",
    diasAbierto: ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado"],
    etiquetas: ["Restaurante", "Alta Cocina", "Colombiana", "Especial", "Gourmet", "El Poblado"]
  },
  {
    id: 35,
    nombre: "Mondongo's El Poblado",
    direccion: "Cl 10 #38-38, El Poblado, Medellín",
    descripcion: "Famoso por sus platos típicos antioqueños, especialmente los mondongos.",
    resena: "⭐⭐⭐⭐ (4.4/5)",
    presupuesto: "$35,000 - $60,000",
    imagen: "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSzjtEJD1yycLwAjYhimZby2_xUpdTf4gH46oqLkjrxgajxYWM8XAIvo03Ow_sm8r6tDLKtMR9jvbzARoOcrMTaFf4H1LqCaFUrKNxk39ZNbLZPwep_Xy3et7P85akUGUUUXrWqbIHMucssN=s680-w680-h510-rw",
    horarioApertura: "11:00 AM",
    horarioCierre: "10:00 PM",
    diasAbierto: ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"],
    etiquetas: ["Restaurante", "Típico", "Antioqueño", "Mondongo", "El Poblado", "Tradicional"]
  },
  {
    id: 36,
    nombre: "Cariñito Mío Café",
    direccion: "Cra 44 #2055, El Poblado, Medellín",
    descripcion: "Clásico de Laureles para disfrutar micheladas y comida típica en un lindo restaurante.",
    resena: "⭐⭐⭐⭐ (4.4/5)",
    presupuesto: "$25,000 - $45,000",
    imagen: "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSwxf7t6daEvcBDyQyxAD27JSkE5Y0OLwaaTc8cbG915rXH49cd_XqDo6WH4sVCszaURMC65THpISfVXyBRoQyH9MR7GXLqRyv43Az0VOXLD4SzhKsVSynsMy9n-V_kUu8zhposM=s680-w680-h510-rw",
    horarioApertura: "11:00 AM",
    horarioCierre: "11:00 PM",
    diasAbierto: ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"],
    etiquetas: ["Restaurante", "Micheladas", "Típico", "Laureles", "Clásico", "Comida"]
  },
  {
    id: 37,
    nombre: "Parque Juanes de la Paz",
    direccion: "Cra. 65 #96A-10, Castilla, Medellín",
    descripcion: "Parque con esculturas del artista Juanes y espacios para deporte.",
    resena: "⭐⭐⭐⭐ (4.3/5)",
    presupuesto: "Gratis",
    imagen: "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSz8S91zcCatuv9n7Qg7qxjeyy11CnCZ7HApxu83ZIDRzDvjadu_eGM5HTxJewAQfBAH4o1inEV_GUo2HeUXM84HtIwXU58B0Fp_Ft4lYDep1it-qiwCM_1ZgR0Xzso2DPnhjshvAg=s680-w680-h510-rw",
    horarioApertura: "06:00 AM",
    horarioCierre: "08:00 PM",
    diasAbierto: ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"],
    etiquetas: ["Parque", "Juanes", "Esculturas", "Deporte", "Gratis", "Castilla"]
  },
  {
    id: 38,
    nombre: "Parque Biblioteca España",
    direccion: "Cl. 107a #Cra 33B # 107A-100, Santo Domingo Savio I, Medellín",
    descripcion: "Icono arquitectónico en la comuna 1, con biblioteca y vistas impresionantes.",
    resena: "⭐⭐⭐⭐ (4.7/5)",
    presupuesto: "Gratis",
    imagen: "https://lh3.googleusercontent.com/p/AF1QipP916g9oJ7nD4HCPk99yk33jGgM06OUCAWzVcs=s680-w680-h510-rw",
    horarioApertura: "09:00 AM",
    horarioCierre: "07:00 PM",
    diasAbierto: ["Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"],
    etiquetas: ["Parque", "Biblioteca", "Arquitectura", "Vistas", "Gratis", "Comuna 1"]
  },
  {
    id: 39,
    nombre: "Parque de El Poblado",
    direccion: "Cra. 43A #1S-150, El Poblado",
    descripcion: "Parque principal del barrio El Poblado, ideal para encuentros casuales.",
    resena: "⭐⭐⭐⭐ (4.3/5)",
    presupuesto: "Gratis",
    imagen: "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSx0VkjaW7PLaXvpD0oYwLmVsq5Pxuy5Ipw0nkZ0qT3MaTYzJ1u4A5hug0rzMk73lAM6IsLkrT9eEkZfAyRuCvFg7j8gPCfp-eaZ2NAr2v25vbNqv8P12xXg3bOy5A32_h2W4wCeAw=s680-w680-h510-rw",
    horarioApertura: "06:00 AM",
    horarioCierre: "10:00 PM",
    diasAbierto: ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"],
    etiquetas: ["Parque", "El Poblado", "Encuentros", "Social", "Gratis", "Barrio"]
  },
  {
    id: 40,
    nombre: "Ecoparque Los Salados",
    direccion: "Represa, Av. Las Palmas #Km. 27, Los Salados, La Fe, Retiro, Antioquia",
    descripcion: "Parque ecológico con piscinas naturales y senderos en Envigado.",
    resena: "⭐⭐⭐⭐ (4.5/5)",
    presupuesto: "$15,000 - $30,000",
    imagen: "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSz60dDQAoEZ5c9rLJJM762RB5rgPvM1MoR-wSNANaJ96Vw1yYw3Ni5D5M52GvS09TdzkiKMINN7lC2Y05Q_Oc2rBpyOc8EQcpOPtl9qtTa3ehCsx938vERCyCNZxuMwJE93-Spw=s680-w680-h510-rw",
    horarioApertura: "08:00 AM",
    horarioCierre: "05:00 PM",
    diasAbierto: ["Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"],
    etiquetas: ["Ecoparque", "Naturaleza", "Piscinas", "Senderos", "Envigado", "Familiar"]
  },
  {
    id: 41,
    nombre: "Teatro Metropolitano",
    direccion: "Cl. 41 #57-30, Medellín",
    descripcion: "Importante escenario cultural para obras de teatro, conciertos y eventos.",
    resena: "⭐⭐⭐⭐⭐ (4.7/5)",
    presupuesto: "$30,000 - $100,000",
    imagen: "https://lh3.googleusercontent.com/p/AF1QipNfFP9VyaSBo0lpm9-77zEEFHhTmzUbSjGH3UO0=s680-w680-h510-rw",
    horarioApertura: "09:00 AM",
    horarioCierre: "10:00 PM",
    diasAbierto: ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"],
    etiquetas: ["Teatro", "Cultural", "Conciertos", "Eventos", "Escenario", "Importante"]
  },
  {
    id: 42,
    nombre: "Teatro Lido",
    direccion: "Cra. 42 #52-20, La Candelaria, Medellín",
    descripcion: "Teatro histórico restaurado, emblemático del centro de Medellín.",
    resena: "⭐⭐⭐⭐ (4.5/5)",
    presupuesto: "$25,000 - $80,000",
    imagen: "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSxXT7lRN6T_vIC03KpCEgkbCy1C9THjaJPJgEBiiXANWjpmUtnaEfAAnO0iyrKNAtbEO28jJ57km66eeWwHWGel5uv9a-M_toN5SoQRec51RsPTqVAVc6Ht8PX6Ks8dsnS6EXYIJg=s680-w680-h510-rw",
    horarioApertura: "10:00 AM",
    horarioCierre: "09:00 PM",
    diasAbierto: ["Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"],
    etiquetas: ["Teatro", "Histórico", "Restaurado", "Centro", "Emblemático", "Cultural"]
  },
  {
    id: 43,
    nombre: "Planetario Medellín",
    direccion: "Cra. 52 #71-117, Medellín",
    descripcion: "Centro de ciencia y astronomía con proyecciones y exhibiciones interactivas.",
    resena: "⭐⭐⭐⭐ (4.6/5)",
    presupuesto: "$15,000 - $25,000",
    imagen: "https://lh3.googleusercontent.com/p/AF1QipPF-Ye0ZKJPZROUIIp8AhT96HHECW90GSlvmRsY=s680-w680-h510-rw",
    horarioApertura: "09:00 AM",
    horarioCierre: "05:30 PM",
    diasAbierto: ["Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"],
    etiquetas: ["Planetario", "Ciencia", "Astronomía", "Interactivo", "Educativo", "Familiar"]
  },
  {
    id: 44,
    nombre: "Cervantes Cafe",
    direccion: "Pasaje Cervantes, Cra. 42A #48-46, Medellín",
    descripcion: "Café con ambiente bohemio en el pasaje Cervantes del centro.",
    resena: "⭐⭐⭐⭐ (4.4/5)",
    presupuesto: "$15,000 - $30,000",
    imagen: "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSzO5Ga0VerKydK16lFYc8Gfy_vO2CYB68fT-02HrBNMYRZy6YbSxgYXV3M4JlFWpcCHlZuEk53uITM1EI4X5g_yTVLI6FtS-gXMQFVwAOdubOyIf5o3zeblofmcZ572YplyZBkcsA=s680-w680-h510-rw",
    horarioApertura: "11:00 AM",
    horarioCierre: "09:00 PM",
    diasAbierto: ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado"],
    etiquetas: ["Café", "Bohemio", "Centro", "Pasaje Cervantes", "Cultural", "Arte"]
  },
  {
    id: 45,
    nombre: "Café Leones",
    direccion: "Cra. 37 #8-66, El Poblado, Medellín",
    descripcion: "Cafetería con ambiente acogedor y deliciosa repostería.",
    resena: "⭐⭐⭐⭐ (4.5/5)",
    presupuesto: "$20,000 - $40,000",
    imagen: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/15/46/c8/54/que-buen-espacio.jpg?w=1000&h=-1&s=1",
    horarioApertura: "08:00 AM",
    horarioCierre: "09:00 PM",
    diasAbierto: ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"],
    etiquetas: ["Café", "Acogedor", "Repostería", "El Poblado", "Delicioso", "Postres"]
  },
  {
    id: 46,
    nombre: "Billares América",
    direccion: "Cl. 53 #45-82, La Candelaria, Medellín",
    descripcion: "Salón de billares clásico en el centro de la ciudad.",
    resena: "⭐⭐⭐⭐ (4.3/5)",
    presupuesto: "$10,000 - $25,000",
    imagen: "https://barcelonapoolbilliards.academy/wp-content/uploads/2022/02/F1.001.1-Billar-Americano.jpg",
    horarioApertura: "11:00 AM",
    horarioCierre: "02:00 AM",
    diasAbierto: ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado"],
    etiquetas: ["Billares", "Clásico", "Centro", "Entretenimiento", "Amigos", "Deporte"]
  },
  {
    id: 47,
    nombre: "Súper Bowling",
    direccion: "Centro Comercial San Diego, Local 201, Medellín",
    descripcion: "Bolera moderna con múltiples pistas y ambiente familiar.",
    resena: "⭐⭐⭐⭐ (4.4/5)",
    presupuesto: "$25,000 - $50,000",
    imagen: "https://brunswickbowling.nyc3.cdn.digitaloceanspaces.com/production/transforms/galleries/Superbowling-Medellin-Colombia/328961/Superbowling_Medellin_Colombia_16x9_0122-09_150_21_cc6833e5b379cf061e625296f23dfd1b.jpg",
    horarioApertura: "10:00 AM",
    horarioCierre: "11:00 PM",
    diasAbierto: ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"],
    etiquetas: ["Bolera", "Familiar", "Entretenimiento", "Moderno", "San Diego", "Diversión"]
  },
  {
    id: 48,
    nombre: "La Grietta eSport",
    direccion: "Cra. 43G #18-50, El Poblado, Medellín",
    descripcion: "Centro de esports y gaming con equipos de alta gama.",
    resena: "⭐⭐⭐⭐ (4.6/5)",
    presupuesto: "$15,000 - $35,000",
    imagen: "https://revistacosas.mx/wp-content/uploads/2022/03/level.png",
    horarioApertura: "12:00 PM",
    horarioCierre: "12:00 AM",
    diasAbierto: ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"],
    etiquetas: ["Esports", "Gaming", "Alta Gama", "Videojuegos", "El Poblado", "Tecnología"]
  },
  {
    id: 49,
    nombre: "Mercado de San Alejo",
    direccion: "Cra. 58 #55-41, La Candelaria, Medellín",
    descripcion: "Mercado de pulgas los fines de semana con artesanías y antigüedades.",
    resena: "⭐⭐⭐⭐ (4.5/5)",
    presupuesto: "Gratis - $50,000",
    imagen: "https://lh3.googleusercontent.com/p/AF1QipOZlI9snUtRgrJlw5tUmqROntFUniSQTRFt0K9B=s680-w680-h510-rw",
    horarioApertura: "08:00 AM",
    horarioCierre: "06:00 PM",
    diasAbierto: ["Sábado", "Domingo"],
    etiquetas: ["Mercado", "Artesanías", "Antigüedades", "Pulgas", "Fines de Semana", "Centro"]
  },
  {
    id: 50,
    nombre: "Mall de la Mota",
    direccion: "Cl. 51 #45-55, La Candelaria, Medellín",
    descripcion: "Centro comercial en el centro con variedad de locales.",
    resena: "⭐⭐⭐⭐ (4.2/5)",
    presupuesto: "$20,000 - $60,000",
    imagen: "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSzwh0KU1BVtbA9kQnOca0fUaP8wGYgZlNLksLnvr_V-lrn0zMK_A2bDxGZENQBeh2oZKMjElq6Vu65wTwON85XdGpcI4PAKCHngLi-8T1BEU7EK4ALqPzRz7tG3egL0a4aqKgvwx9896ZkF=s680-w680-h510-rw",
    horarioApertura: "09:00 AM",
    horarioCierre: "08:00 PM",
    diasAbierto: ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"],
    etiquetas: ["Centro Comercial", "Compras", "Variedad", "Centro", "Tiendas", "Comercial"]
  },
  {
    id: 51,
    nombre: "Mall Complex Ditaires",
    direccion: "Cra. 65 #484-527, Medellín",
    descripcion: "Centro comercial en la zona norte de Medellín.",
    resena: "⭐⭐⭐⭐ (4.3/5)",
    presupuesto: "$25,000 - $70,000",
    imagen: "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSzid4C8B90EeN6-U8FO6EO6pBPkKjCcsYO39vLHZajgGbprorIOzWRWG370c2afAXUosGxxRYsIkdinoD90MGzFiisSCLgW275H3_Z1Q_myIUWqhJpq-91Pc7t3IE7iJLcqdlZy=s680-w680-h510-rw",
    horarioApertura: "09:00 AM",
    horarioCierre: "09:00 PM",
    diasAbierto: ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"],
    etiquetas: ["Centro Comercial", "Norte", "Compras", "Variedad", "Ditaires", "Zona Norte"]
  },
  {
    id: 52,
    nombre: "Pueblito Paisa",
    direccion: "Cerro Nutibara, Medellín",
    descripcion: "Réplica de un pueblo antioqueño tradicional en la cima del cerro Nutibara.",
    resena: "⭐⭐⭐⭐ (4.5/5)",
    presupuesto: "Gratis",
    imagen: "https://www.infobae.com/resizer/v2/XAA7V7QQHRHR5DN7JQ7BEA3R6Q.jpg?auth=edccd71f5d9ced5e4c375e829005a918c3b0c0ad57937dcf6997367a75b80454&smart=true&width=768&height=432&quality=85",
    horarioApertura: "08:00 AM",
    horarioCierre: "10:00 PM",
    diasAbierto: ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"],
    etiquetas: ["Pueblito", "Tradicional", "Antioqueño", "Cerro Nutibara", "Turístico", "Gratis"]
  },
  {
    id: 53,
    nombre: "Parque Lleras",
    direccion: "El Poblado, Medellín",
    descripcion: "Epicentro de la vida nocturna en Medellín con bares y restaurantes.",
    resena: "⭐⭐⭐⭐ (4.4/5)",
    presupuesto: "$30,000 - $80,000",
    imagen: "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSzvrFmu5lBK65oAj0uYXMb6sdOJvWEMF6ry5Dic6iwEludp6bsmXLpMdqxhzvGARMmZGlPs8CeH8tS_ClgBAzdseJ48ZJz60JLvjeRw-XMwsxn5NF7nsudDWRcMnYGYs5TpzU4XJQ=s680-w680-h510-rw",
    horarioApertura: "24 horas",
    horarioCierre: "24 horas",
    diasAbierto: ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"],
    etiquetas: ["Parque", "Vida Nocturna", "Bares", "Restaurantes", "El Poblado", "24 horas"]
  },
  {
    id: 54,
    nombre: "Cerro Pan de Azúcar",
    direccion: "Cerro Pan de Azúcar, Medellín",
    descripcion: "Mirador natural con vistas panorámicas de la ciudad.",
    resena: "⭐⭐⭐⭐ (4.6/5)",
    presupuesto: "Gratis",
    imagen: "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSw2GSkCUx70jCMDrdUB6UP2vO10VCQBuY7022nSZCL02-BoKaq6NaZty-HVTILIl6xBv6WMVpU8lzmp-RbE9Xd29N0yYRSFVpALylsCM0p3M5dV82iVBQn3VC06vF_jU3E8PXRj=s680-w680-h510-rw",
    horarioApertura: "06:00 AM",
    horarioCierre: "06:00 PM",
    diasAbierto: ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"],
    etiquetas: ["Cerro", "Mirador", "Vistas", "Panorámico", "Gratis", "Naturaleza"]
  },
  {
    id: 55,
    nombre: "Mountain Park",
    direccion: "Vía a Las Palmas, Medellín",
    descripcion: "Parque de aventuras en las montañas con actividades al aire libre.",
    resena: "⭐⭐⭐⭐ (4.5/5)",
    presupuesto: "$40,000 - $80,000",
    imagen: "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSzuvm0vbBG-EZiC0Q_z1gxF0sbvJto07l-OionQr8Cvxr6TVobNcf9djJRBNQvdaBPWFjIwRVOmryNFUqvR4b_Advzj1YFSJg3B4uhEN0Otk7ICeL7drDTcxwm8HeIgFm0VK-k=s680-w680-h510-rw",
    horarioApertura: "09:00 AM",
    horarioCierre: "06:00 PM",
    diasAbierto: ["Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"],
    etiquetas: ["Parque", "Aventuras", "Montaña", "Aire Libre", "Deportes", "Extremo"]
  },
  {
    id: 56,
    nombre: "Mirador del Cielo",
    direccion: "Alto de Las Palmas, Medellín",
    descripcion: "Mirador espectacular con vistas sobre el valle de Aburrá.",
    resena: "⭐⭐⭐⭐⭐ (4.8/5)",
    presupuesto: "Gratis",
    imagen: "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSx-qFoonOz25kytYvBZvqkxiKA7BhYABtP1D7nYGRKtWZv2peSMylp0OBnAQVcyXCsqrDDrwAEn8fceNbJGtxDzxWpsaauD-pft2xVCZN6S_vcSbJlgPMRc78k6RanCP4a3GqDM=s680-w680-h510-rw",
    horarioApertura: "24 horas",
    horarioCierre: "24 horas",
    diasAbierto: ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"],
    etiquetas: ["Mirador", "Vistas", "Valle de Aburrá", "24 horas", "Gratis", "Panorámico"]
  },
  {
    id: 57,
    nombre: "UVA del Tesoro",
    direccion: "Cra. 76 #41-55, Medellín",
    descripcion: "Unidad de Vida Articulada con espacios deportivos y culturales.",
    resena: "⭐⭐⭐⭐ (4.4/5)",
    presupuesto: "Gratis",
    imagen: "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSzbrvheq-_MIK3sUWSE85kKnLDPhTSfRdbwFRYvUnX8H87gWlD8yH7sfgmaFdNepXEgvg9lg4bBZZP3J6VpKhz__j_sB-8JCPTAO1JsK0N7n-OnXUyAK321laS6yxSGoHpO7Jj-=s680-w680-h510-rw",
    horarioApertura: "08:00 AM",
    horarioCierre: "08:00 PM",
    diasAbierto: ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"],
    etiquetas: ["UVA", "Deportivo", "Cultural", "Comunitario", "Gratis", "Espacios Públicos"]
  },
  {
    id: 58,
    nombre: "Parque de las Aguas",
    direccion: "Cra. 52 #71-117, Medellín",
    descripcion: "Parque con fuentes y juegos de agua, ideal para familias.",
    resena: "⭐⭐⭐⭐ (4.5/5)",
    presupuesto: "$10,000 - $20,000",
    imagen: "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSxIJlYoBZkySWL6Af1R0hyr4Y-yR7OlwiaUfbD1nQMUosRZ6l9v6G6AgkjdT1O9dj8qr7y9eTtBEyCOm3W0B99QpZyvZfSZJHy6qGahe-zDOyy21Kztf-AoER44hAsrv6fU51PD=s680-w680-h510-rw",
    horarioApertura: "10:00 AM",
    horarioCierre: "06:00 PM",
    diasAbierto: ["Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"],
    etiquetas: ["Parque", "Agua", "Familiar", "Juegos", "Fuentes", "Niños"]
  },
  {
    id: 59,
    nombre: "Parque Juan Pablo II",
    direccion: "Cra. 76 #44-12, Medellín",
    descripcion: "Parque con toboganes y áreas recreativas para niños.",
    resena: "⭐⭐⭐⭐ (4.3/5)",
    presupuesto: "Gratis",
    imagen: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2b/2e/e1/90/toboganes.jpg?w=1000&h=-1&s=1",
    horarioApertura: "08:00 AM",
    horarioCierre: "07:00 PM",
    diasAbierto: ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"],
    etiquetas: ["Parque", "Niños", "Toboganes", "Recreativo", "Familiar", "Gratis"]
  },
  {
    id: 60,
    nombre: "Asados La 80",
    direccion: "Cra. 80 #39-55, Laureles, Medellín",
    descripcion: "Restaurante especializado en carnes y parrilladas.",
    resena: "⭐⭐⭐⭐ (4.4/5)",
    presupuesto: "$35,000 - $70,000",
    imagen: "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSzzECL-omD8cvaSipkYSarL6tuiO_7ni_MUPLBUXEdo85z4te0xPKBHS37eFsy_vl65p5cREY0mMmB2jNhtBa7UQH-2PnsBmNJPNDItobmRRckml7zg4di90o7dyux4J7UCJqE9VA=s680-w680-h510-rw",
    horarioApertura: "11:00 AM",
    horarioCierre: "10:00 PM",
    diasAbierto: ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"],
    etiquetas: ["Restaurante", "Carnes", "Parrillada", "Laureles", "Asados", "Típico"]
  },
  {
    id: 61,
    nombre: "Mozzafiato Art Pizzería",
    direccion: "Cra. 36 #10-49, El Poblado, Medellín",
    descripcion: "Pizzería artesanal con masa fermentada y ingredientes premium.",
    resena: "⭐⭐⭐⭐⭐ (4.7/5)",
    presupuesto: "$40,000 - $75,000",
    imagen: "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSwCO0mmXWeYnOIwp1CWQFNNEzOWO7WMqvYfag-9SIPZcIvdGVAN2s7PIZO25_xKD04cLOlKTXP7WRjXxSuizNPvQ6Awi7nQp8LyXrvWI4vJB8ErJnjm_qgq7c9hVhfvoRTNVG2j-nrw881x=s680-w680-h510-rw",
    horarioApertura: "12:00 PM",
    horarioCierre: "10:00 PM",
    diasAbierto: ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"],
    etiquetas: ["Pizzería", "Artesanal", "Premium", "Masa Fermentada", "El Poblado", "Italiana"]
  },
  {
    id: 62,
    nombre: "FRESEO Parchadero Laureles",
    direccion: "Cq. 70 #6-30, Laureles, Medellín",
    descripcion: "Lugar para 'parchar' con amigos, cócteles y ambiente relajado.",
    resena: "⭐⭐⭐⭐ (4.5/5)",
    presupuesto: "$25,000 - $50,000",
    imagen: "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSyE6-plJC0wi477QRm-U4SLtNcIe_3DbwZcRCuAXEa2rIkoPktnP6u91TUn6dVYjQSY1I-ofzLkMOqTo8Z0VRUv2LmCNrjkSSeLOJNNCUXwdUIyltUpNJF_Kzn6T4vjVBMn0p3JfA=s680-w680-h510-rw",
    horarioApertura: "04:00 PM",
    horarioCierre: "01:00 AM",
    diasAbierto: ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado"],
    etiquetas: ["Parchadero", "Cócteles", "Amigos", "Relajado", "Laureles", "Social"]
  },
  {
    id: 63,
    nombre: "La 4 Sur",
    direccion: "Cl. 10 Sur #43-55, El Poblado, Medellín",
    descripcion: "Bar y restaurante con terraza y ambiente vibrante.",
    resena: "⭐⭐⭐⭐ (4.4/5)",
    presupuesto: "$30,000 - $60,000",
    imagen: "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSytXrlJi3QTj9citxU8xkVJrO_IEzJWy8QKjZNkEfhOQd80oEogU97WO5C-W-XxxEU6JMbSKBPeC7Uur76Jk-u0nLamMfrK6Ia-SynMfHZcYoRz1uvlbPshC0IKMOnTbjo9pLJJlf3lR2Ug=s680-w680-h510-rw",
    horarioApertura: "05:00 PM",
    horarioCierre: "02:00 AM",
    diasAbierto: ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado"],
    etiquetas: ["Bar", "Restaurante", "Terraza", "Vibrante", "El Poblado", "Social"]
  },
  {
    id: 64,
    nombre: "Ámbar Violetazul",
    direccion: "Cra. 36 #10-50, El Poblado, Medellín",
    descripcion: "Restaurante-bar con terraza y cócteles de autor.",
    resena: "⭐⭐⭐⭐ (4.6/5)",
    presupuesto: "$45,000 - $85,000",
    imagen: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0f/35/79/13/laterrazadeambar.jpg?w=1000&h=-1&s=1",
    horarioApertura: "06:00 PM",
    horarioCierre: "02:00 AM",
    diasAbierto: ["Miércoles", "Jueves", "Viernes", "Sábado"],
    etiquetas: ["Restaurante", "Bar", "Terraza", "Cócteles Autor", "El Poblado", "Exclusivo"]
  },
  {
    id: 65,
    nombre: "BIFTEK",
    direccion: "Cra. 37 #8-34, El Poblado, Medellín",
    descripcion: "Steakhouse premium con cortes de carne de alta calidad.",
    resena: "⭐⭐⭐⭐⭐ (4.8/5)",
    presupuesto: "$80,000 - $150,000",
    imagen: "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSwpZFHly13OgslhVnwD14SWaEaCvTu_fcQUzVGrig9k1DZQnp47Q6v6kL1nK5kYg-c4mwwzD7ha2yLod4G5THdLPfePYgY4CSHOHQMa-I3YyMk2oxOebDcqL9FHIQ-jeyWe_CUmNw=s680-w680-h510-rw",
    horarioApertura: "12:00 PM",
    horarioCierre: "11:00 PM",
    diasAbierto: ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado"],
    etiquetas: ["Steakhouse", "Premium", "Carnes", "Alta Calidad", "El Poblado", "Gourmet"]
  },
  {
    id: 66,
    nombre: "Náufrago Rooftop",
    direccion: "Cra. 36 #10-48, El Poblado, Medellín",
    descripcion: "Terraza con vista panorámica y ambiente sofisticado.",
    resena: "⭐⭐⭐⭐ (4.7/5)",
    presupuesto: "$50,000 - $90,000",
    imagen: "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSwzNDtBb11Y6A9pHXX5LE6XMAZsc2lPZvYV8Jmxm7u3Z98BbfAM-8lacJ8aYqribZLPNHShppW05r_MRui0B0i4nw5HzRGIQzVs-EIhC5mHIsWG6pHlj40F5JVSwYdOfWp7qWhsPh8MhLB6=s680-w680-h510-rw",
    horarioApertura: "05:00 PM",
    horarioCierre: "02:00 AM",
    diasAbierto: ["Miércoles", "Jueves", "Viernes", "Sábado"],
    etiquetas: ["Rooftop", "Terraza", "Vistas", "Sofisticado", "El Poblado", "Exclusivo"]
  },
  {
    id: 67,
    nombre: "Constelaciones Macromural",
    direccion: "Comuna 13, Medellín",
    descripcion: "Macromural que representa constelaciones en las fachadas de la comuna 13.",
    resena: "⭐⭐⭐⭐⭐ (4.8/5)",
    presupuesto: "Gratis",
    imagen: "https://estaticos.elcolombiano.com/binrepository/998x562/109c0/780d562/none/11101/VGOA/camanrique-grafitis-3-42341457-20230509203923_44010483_20231219101409.jpg",
    horarioApertura: "24 horas",
    horarioCierre: "24 horas",
    diasAbierto: ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"],
    etiquetas: ["Macromural", "Arte Urbano", "Constelaciones", "Comuna 13", "Gratis", "24 horas"]
  },
  {
    id: 68,
    nombre: "Comuna 13",
    direccion: "Comuna 13, Medellín",
    descripcion: "Famosa por sus grafitis, escaleras eléctricas y transformación social.",
    resena: "⭐⭐⭐⭐⭐ (4.9/5)",
    presupuesto: "Gratis (Tour opcional $20,000-$40,000)",
    imagen: "https://www.infobae.com/resizer/v2/TUYTDETVPNDGLIWIWILQH2TY6Q.jpg?auth=ed5e137e25e1029c9b38f8e7b4dcb8a7b3ce9f743ff3448efed4f3d84888a81a&smart=true&width=992&height=558&quality=85",
    horarioApertura: "08:00 AM",
    horarioCierre: "06:00 PM",
    diasAbierto: ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"],
    etiquetas: ["Comuna 13", "Grafiti", "Transformación", "Social", "Turístico", "Gratis"]
  },
  {
    id: 69,
    nombre: "Palacio Nacional",
    direccion: "Cra. 52 #48-45, La Candelaria, Medellín",
    descripcion: "Edificio histórico que alberga tribunales y es patrimonio arquitectónico.",
    resena: "⭐⭐⭐⭐ (4.4/5)",
    presupuesto: "Gratis",
    imagen: "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSwiaC30ePVLr9gRz_bP8jpVs6iQrvaohdhFSEHHeeppak8EWI1AsochaFTgLUNX3EeFGdTJQdDx89SMYBxxCauB2qk1UFrn1UlTk6_rgPHnKIUQ9exwq7ROvWpGIJ5LjY2U7g=s680-w680-h510-rw",
    horarioApertura: "08:00 AM",
    horarioCierre: "05:00 PM",
    diasAbierto: ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes"],
    etiquetas: ["Palacio", "Histórico", "Arquitectura", "Patrimonio", "Centro", "Gratis"]
  },
  {
    id: 70,
    nombre: "Tranvía Bulevar",
    direccion: "Centro de Medellín",
    descripcion: "Sistema de tranvía moderno que conecta el centro de la ciudad.",
    resena: "⭐⭐⭐⭐ (4.5/5)",
    presupuesto: "$2,500 - $5,000",
    imagen: "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSzGk92FhMiebuph3ARaaTpoi_EFMgvjR-UgvSdMpyK4gSva40oGTROuw6jq4qiC3n3rq1-8PI9MP56Gjl9EqnNigRsgNTyoAb0sXgGKXLODRSTtZ0L5T5BvMM0O873pYv6iES0=s680-w680-h510-rw",
    horarioApertura: "05:00 AM",
    horarioCierre: "11:00 PM",
    diasAbierto: ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"],
    etiquetas: ["Tranvía", "Transporte", "Moderno", "Centro", "Movilidad", "Público"]
  },
  {
    id: 71,
    nombre: "Manrique la 45",
    direccion: "Manrique, Medellín",
    descripcion: "Zona comercial y residencial tradicional de Medellín.",
    resena: "⭐⭐⭐⭐ (4.3/5)",
    presupuesto: "Varía según establecimiento",
    imagen: "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSx24W1casJCMPYST4_ELAcNP-xUMPT5fNEyJrJJgN02W4xFPJZaCVSA_7jFBTMeAxObQ4UEgW3zoiMmg0N3UohDKOd0v2LDnqOSfoyf7RfxSKvaR_8T_KQpgp-jmyIEX2oL9WiR=s680-w680-h510-rw",
    horarioApertura: "08:00 AM",
    horarioCierre: "10:00 PM",
    diasAbierto: ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"],
    etiquetas: ["Zona Comercial", "Manrique", "Tradicional", "Residencial", "Comercio", "Barrio"]
  },
  {
    id: 72,
    nombre: "La Gitana en Las Nubes",
    direccion: "Alto de Las Palmas, Medellín",
    descripcion: "Mirador y restaurante con vista espectacular sobre Medellín.",
    resena: "⭐⭐⭐⭐ (4.6/5)",
    presupuesto: "$50,000 - $100,000",
    imagen: "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSxnfrTuwG1-3lAaTvQ2FEV_PmahyFxwBmwqq7uHKjqvX3raK32bryYmizU7Ts0cwfmSC5WFh7WJg6HZ2vB_97Kg6YFQyROrraiVqlHQvRUyq-YEGQClMDBW2L2YliXW36b63WmuP9S9Zx38=s680-w680-h510-rw",
    horarioApertura: "12:00 PM",
    horarioCierre: "10:00 PM",
    diasAbierto: ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"],
    etiquetas: ["Mirador", "Restaurante", "Vistas", "Alto de Las Palmas", "Espectacular", "Panorámico"]
  },
  {
    id: 73,
    nombre: "Confama Rionegro",
    direccion: "Rionegro, Antioquia",
    descripcion: "Centro recreativo y deportivo de Comfama con piscinas y áreas verdes.",
    resena: "⭐⭐⭐⭐ (4.5/5)",
    presupuesto: "$15,000 - $30,000",
    imagen: "https://viajaporcolombia.com/images//comfama-rionegro.jpg",
    horarioApertura: "09:00 AM",
    horarioCierre: "06:00 PM",
    diasAbierto: ["Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"],
    etiquetas: ["Comfama", "Recreativo", "Deportivo", "Piscinas", "Rionegro", "Familiar"]
  },
  {
    id: 74,
    nombre: "Xtreme Fun Zone",
    direccion: "Centro Comercial Oviedo, El Poblado, Medellín",
    descripcion: "Parque de diversiones indoor con juegos extremos y realidad virtual.",
    resena: "⭐⭐⭐⭐ (4.4/5)",
    presupuesto: "$30,000 - $60,000",
    imagen: "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSzSugA4BHjJG7ayaDGX_7rHRuK-PwMELswABGycI_16oYrK_i2lbhEnmRjWeus7XkoZPzaEywbP2GsJ1UGAgAHzyg1x3v7UU6PtavfhPubRb8CYlJRCgwuD1oQzL3bAW4zP2tSz-Q=s680-w680-h510-rw",
    horarioApertura: "10:00 AM",
    horarioCierre: "10:00 PM",
    diasAbierto: ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"],
    etiquetas: ["Parque", "Diversiones", "Realidad Virtual", "Extremo", "Oviedo", "Indoor"]
  },
  {
    id: 75,
    nombre: "Os Mirador",
    direccion: "Alto de Las Palmas, Medellín",
    descripcion: "Mirador y restaurante con vista panorámica del valle.",
    resena: "⭐⭐⭐⭐ (4.5/5)",
    presupuesto: "$40,000 - $80,000",
    imagen: "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSwNdHFWRssS7Era4nsZoUHUcxTMpTSs4QIjXg971ZqGs1LpV279cCmERRgNzo8FJyuFYeq1SP897uwOQ4NFXkbxvvPH6_S7059698B0J37gVkzEzQr_r9Umyn0m4d30HjB_kV1R=s680-w680-h510-rw",
    horarioApertura: "11:00 AM",
    horarioCierre: "11:00 PM",
    diasAbierto: ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"],
    etiquetas: ["Mirador", "Restaurante", "Vistas", "Alto de Las Palmas", "Panorámico", "Valle", "Tranquilo"]
  }
]


export const topPlaces = [
  {
    id: "1",
    nombre: "Museo de Antioquia",
    tipo: "Museo",
    direccion: "Cl. 52 #52-43, La Candelaria, Medellín",
    descripcion: "Alberga una vasta colección de arte, incluyendo obras de Fernando Botero.",
    imagen: "https://lh3.googleusercontent.com/p/AF1QipNqXffczcrQOepDyQ_5za6nXuthowHd2XlniSkf=s680-w680-h510-rw",
    calificacion: "⭐⭐⭐⭐⭐ (4.6/5)"
  },
  {
    id: "2",
    nombre: "Parque Arví",
    tipo: "Parque",
    direccion: "Vía a, Piedras Blancas, Medellín",
    descripcion: "Parque ecoturístico público, ideal para caminatas y conexión con la naturaleza.",
    imagen: "https://antioquiahoy.co/wp-content/uploads/2025/05/Imagen-de-WhatsApp-2023-08-01-a-las-14.01.47.jpg",
    calificacion: "⭐⭐⭐⭐⭐ (4.7/5)"
  },
  {
    id: "3",
    nombre: "Jardín Botánico de Medellín",
    tipo: "Jardín",
    direccion: "Cl. 73 #51D-14, Aranjuez, Medellín",
    descripcion: "Pulmón verde de la ciudad con una gran variedad de flora.",
    imagen: "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSyXLVd1miK9j7GX6qW3QgUSgycEcTGcEl9LOi89vLD7MoijRJLayiQTHLt4JtHylWWlA3GN_Ho92zZVQ_wgwCIZ4_9RewricvhfdW456ouWlwyv9WoF39cGari4U-6SQvCh1xk29g=s680-w680-h510-rw",
    calificacion: "⭐⭐⭐⭐⭐ (4.7/5)"
  },
  {
    id: "4",
    nombre: "Carmen",
    tipo: "Restaurante",
    direccion: "Cra. 36 #10a-27, El Poblado, Medellín",
    descripcion: "Restaurante de alta cocina colombiana, ideal para ocasiones especiales.",
    imagen: "https://lh3.googleusercontent.com/p/AF1QipPKxxagHQHW4YNu0UbOra12_t10onc3ZFwuXedX=s680-w680-h510-rw",
    calificacion: "⭐⭐⭐⭐⭐ (4.8/5)"
  },
  {
    id: "5",
    nombre: "Mojitos Restaurant Bar",
    tipo: "Restaurante/Bar",
    direccion: "Cra. 36 #10b 28 Segundo Piso. Local 201, El Poblado, Medellín",
    descripcion: "Restaurante-bar vibrante con shows en vivo, cantantes y DJ.",
    imagen: "https://lh3.googleusercontent.com/p/AF1QipPWQmHwSp-8C1qxqPh1hJuMPfDP7c_oloUO9gUX=s680-w680-h510-rw",
    calificacion: "⭐⭐⭐⭐⭐ (4.9/5)"
  },
  {
    id: "6",
    nombre: "Comuna 13",
    tipo: "Atractivo Turístico",
    direccion: "Comuna 13, Medellín",
    descripcion: "Famosa por sus grafitis, escaleras eléctricas y transformación social.",
    imagen: "https://www.infobae.com/resizer/v2/TUYTDETVPNDGLIWIWILQH2TY6Q.jpg?auth=ed5e137e25e1029c9b38f8e7b4dcb8a7b3ce9f743ff3448efed4f3d84888a81a&smart=true&width=992&height=558&quality=85",
    calificacion: "⭐⭐⭐⭐⭐ (4.9/5)"
  },
  {
    id: "7",
    nombre: "The Terrace by Wellcomm",
    tipo: "Rooftop",
    direccion: "Cra. 43E #11-37, El Poblado, Medellín",
    descripcion: "Rooftop moderno con ambiente sofisticado, ideal para disfrutar de cócteles y pizzas con vista al cielo.",
    imagen: "https://resizer.otstatic.com/v2/photos/huge/1/79602324.jpg",
    calificacion: "⭐⭐⭐⭐⭐ (4.9/5)"
  },
  {
    id: "8",
    nombre: "Pergamino Café",
    tipo: "Café",
    direccion: "Cra. 37 #8A-37, El Poblado",
    descripcion: "Cafetería de especialidad, referente de café de calidad en la ciudad.",
    imagen: "https://lh3.googleusercontent.com/p/AF1QipNkBThQyr6BQaL75wjkk1klil8FLM4KJFtB4y2l=s680-w680-h510-rw",
    calificacion: "⭐⭐⭐⭐⭐ (4.7/5)"
  },
  {
    id: "9",
    nombre: "Hija Mia Café",
    tipo: "Café",
    direccion: "Cl. 35 #8-34, El Poblado",
    descripcion: "Café acogedor con deliciosos postres y opciones para celiacos.",
    imagen: "https://lh3.googleusercontent.com/p/AF1QipNkBThQyr6BQaL75wjkk1klil8FLM4KJFtB4y2l=s680-w680-h510-rw",
    calificacion: "⭐⭐⭐⭐⭐ (4.8/5)"
  },
  {
    id: "10",
    nombre: "BIFTEK",
    tipo: "Restaurante",
    direccion: "Cra. 37 #8-34, El Poblado, Medellín",
    descripcion: "Steakhouse premium con cortes de carne de alta calidad.",
    imagen: "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSwpZFHly13OgslhVnwD14SWaEaCvTu_fcQUzVGrig9k1DZQnp47Q6v6kL1nK5kYg-c4mwwzD7ha2yLod4G5THdLPfePYgY4CSHOHQMa-I3YyMk2oxOebDcqL9FHIQ-jeyWe_CUmNw=s680-w680-h510-rw",
    calificacion: "⭐⭐⭐⭐⭐ (4.8/5)"
  }
]